### Test register

@baseUrl = http://localhost:3000/api/v2/users

POST http://localhost:3000/api/v2/users/register
Content-Type: application/json


{
    "username": "AlexExample222",
    "email": "AlexExample222@example.com",
    "password": "12345678222@"
}

### Test login
POST {{baseUrl}}/login
Content-Type: application/json


{
    "email": "AlexExample222@example.com",
    "password": "12345678222@"
}


### The REST Client stores the Set-Cookie header from request #1 automatically.
GET {{baseUrl}}/auth/me

### LOGOUT
POST {{baseUrl}}/auth/logout

###GET user
GET {{baseUrl}}