GET http://localhost:3000/api/v2/users



### Dynamic route
GET http://localhost:3000/api/v2/users/6a06cc4963ff2b943dc169d2

### create new user
POST http://localhost:3000/api/v2/users
Content-Type: application/json

{
  "username":"john2",
  "role":"user",
  "email":"john2@example.com",
  "password":"12345678"
}

### Update
PUT http://localhost:3000/api/v2/users/6a06cc4963ff2b943dc169d2
Content-Type: application/json

{
    "username": "AlexExample",
    "email": "AlexExample@example.com",
    "password": "123456782@"
}


### Delete
DELETE  http://localhost:3000/api/v2/users/6a07534cd4f7ba855b2033b7


### Test register

POST http://localhost:3000/api/v2/users/register
Content-Type: application/json


{
    "username": "AlexExample2",
    "email": "AlexExample2@example.com",
    "password": "123456782@"
}
